### PR TITLE
Turn on GSD cloud ceiling calculation for RRFS dev.

### PR DESCRIPTION
**Pull request by hu5970**
Use GSD cloud ceiling calculation for RRFS experiments.

### CODE REVIEW

**Review by christinaholtNOAA — APPROVED** [review]
Looks good.

**Comment by christinaholtNOAA** [comment]
@hu5970 Do you have the missions to merge the PR?

**Comment by hu5970** [comment]
@christinaholtNOAA Do you mean if I can merge the PR or the purpose of this PR?

Steve has deliverable to evaluate the GSD ceiling in RRFS. This is to make GSD ceiling available in verification and plots in RRFS_dev1.

**Comment by christinaholtNOAA** [comment]
Sorry. There was a typo. I was trying to ask if you have the necessary github permissions to merge the PR. Go ahead and do that if you can.

**Comment by hu5970** [comment]
@christinaholtNOAA I don't have permission to merge.

**Pull request merged**
