### PR TITLE
Turn on GSD cloud ceiling calculation for RRFS dev

### PR DESCRIPTION
**Pull request by hu5970**
Turn on GSD cloud ceiling calculation for RRFS dev.

### CODE REVIEW

**Comment by hu5970** [comment]
We did this for  RRFS_dev branch. But his PR is to put the change to develop branch.

After this PR, all RRFS_devs can start to use the develop branch, which has the latest code as base for Jaymes' work.

**Comment by christinaholtNOAA** [comment]
So this has already been applied to the all the dev runs?

**Comment by hu5970** [comment]
NO, we need to make this PR to get post ready and I need to do another PR to workflow to make it used in dev.

**Comment by hu5970** [comment]
OK, I think my previous reply is not right. 

This has already been applied to the all the dev runs. This commit is to make sure it is still in dev runs when update to UPP develop branch.

**Comment by christinaholtNOAA** [comment]
Ming, I am still very confused. 

I looked through each of the dev runs, and this change has not yet been applied to what is currently running on Jet. 

Also, I'm just now realizing that you opened this PR to develop. This repository will only take changes to develop from the the authoritative repository. It's unclear to me what the intent is here.

**Comment by hu5970** [comment]
If we are not using this change, we should apply this to all devs. After devs use this version of UPP. It will applied to all devs.

We need to use UPP develop branch  for devs and I think can use this branch directly for now. We can also create a new branch identical to current develop branch if you prefer to go this way and please create one.

**Comment by christinaholtNOAA** [comment]
We will not hold onto any changes in develop in this fork. If we need to use the top of develop without changes, we can. The purpose of RRFS_dev is to hold onto our modifications that don't exist in develop. If we need to update RRFS_dev to the top of EMC's develop we can. Please open this PR to RRFS_dev instead, if you want these changes applied to the RRFS_dev runs.

**Comment by hu5970** [comment]
Christina,

Please delete the current RRFS_dev branch and make the same name branch
based on the current develop branch. Or open the write permission and I
will make a new one first?

Thanks,
Ming

**Comment by christinaholtNOAA** [comment]
Ming, those are not appropriate avenues for the RRFS_dev branch. Can you please tell me what the goal for UPP is for the RRFS dev runs? Maybe that would help us determine the appropriate git solution? 

Are the modifications that are included in PR #2 not the same as those in PR #1 ? 

The RRFS_dev branch is up to date with the top of NOAA-EMC develop, and includes our changes. If you want code with all the latest, that is what you should be using.

**Comment by hu5970** [comment]
Christina,

We don't have any code change for UPP on top of develop branch so far but
we will have something later. The current work is to bring us to the top of
the development and start to work on our own RRFS UPP development.

PR #1 and PR 2 are the same control file modification, but toward different
branches because we will use different branch for RRFS devs.

For the future development, I now think it is better to build a new branch
based on develop. It will take more work to sync but cannot avoid some
confusion. We don't need current RRFS_dev branch anymore and I think we can
delete that branch and use that name for the new branch based on current
develop. So I can have a clean PR (#3, same as #1 and #2) to get that
branch ready for devs and development.

Does this make sense?

Thanks,
Ming

**Comment by christinaholtNOAA** [comment]
Ming,

The goal of these RRFS_dev branches (ones we maintain in the different NOAA-GSL forks) is to have long-lived records of what's been running in the real time runs. We absolutely need to keep RRFS_dev around and the plan is to continue using it for all of our development work. We will not be making changes to the develop branch in our forks of UFS repositories.

If we need drastically different versions of code running in each of our RRFS_dev runs, then we can consider creating RRFS_dev1-4 as we've done for regional_workflow.

When our group needs to do any development work for RRFS development runs, it should start from RRFS_dev. RRFS_dev is completely up to date with the latest NOAA-EMC develop and has a couple of our configuration changes. If we want to feed those changes back to the authoritative repository, we can. 

I don't know what you mean by not needing the RRFS_dev branch any more. Removing it will only lead to more confusion. Maybe we should plan an in-person meeting to discuss the misunderstanding here.

**Comment by hu5970** [comment]
Christina,

Did you sync NOAA-GSL/EMC_post/RRFS_dev to the NOAA-GSL/EMC_post/develop
branch when you sync the NOAA-EMC/EMC_post/develop branch?
If so, we don't need to change the UPP repository for dev to use UPP. BUt
need to change the workflow now.

We can save UPP code management discussion later because we need to bring
more relative colleagues into the discussion, especially Jaymes.

Thanks,
Ming

**Comment by christinaholtNOAA** [comment]
I synced both the NOAA-GSL:develop and the NOAA-GSL:RRFS_dev branches with NOAA-EMC:develop branch at the same time. There have been no further updates to NOAA-EMC:develop since that sync.

**Pull request closed without merging**
