### PR TITLE
Bringing in visibility variable which includes effect of blowing snow.

### PR DESCRIPTION
**Pull request by EricJames-NOAA**
After sync with authoritative EMC develop branch, I need to bring back in the GSL code additions to output a second visibility variable which includes the effect of visibility.

### CODE REVIEW

**Comment by guoqing-noaa** [comment]
@EricJames-NOAA  Will you commit this PR back to EMC/UPP before SFE?

**Comment by EricJames-NOAA** [comment]
> @EricJames-NOAA Will you commit this PR back to EMC/UPP before SFE?

@guoqing-noaa no, this code is not needed for SFE.  It's just for our own internal evaluation of the blowing snow effect in the visibility.  Once we are satisfied with the code, we can add it to EMC/UPP, but we will just have one unified visibility rather than the two I include here for our evaluation.

**Comment by guoqing-noaa** [comment]
Thanks, @EricJames-NOAA !
So you will manually update the UPP component in your or realtime runs?

**Comment by EricJames-NOAA** [comment]
@guoqing-noaa yes that's right!  Just in RRFS-B...the only impact will be the one additional variable.

**Review by hu5970 — APPROVED** [review]

**Pull request merged**
